name: inotip-buyer
version: "1.0.0"
summary: Hello World Electron app
description: |
  Simple Hello World Electron app as an example
grade: stable
confinement: strict
base: core22

apps:
  yt-dlp:
    command: bin/inotip-buyer
    plugs: [home, network, network-bind, removable-media]

parts:
  yt-dlp:
    plugin: python
    source: https://github.com/inotip/buyer.git
