name: inotip-buyer
version: "1.0.0"
summary: Hello World Electron app
description: |
  Simple Hello World Electron app as an example
  
grade: stable
confinement: classic

apps:
  inotip-buyer:
    command: electron-launch $SNAP/usr/share/inotip-buyer/bin/inotip-buyer --no-sandbox
    common-id: inotip-buyer.desktop
    environment:
      GSETTINGS_SCHEMA_DIR: $SNAP/usr/share/glib-2.0/schemas

  url-handler:
    command: electron-launch $SNAP/usr/share/inotip-buyer/bin/inotip-buyer --open-url --no-sandbox
    environment:
      GSETTINGS_SCHEMA_DIR: $SNAP/usr/share/glib-2.0/schemas
      
      
gnome:
    plugin: nil
    build-packages:
      - software-properties-common
    override-pull: |
      add-apt-repository -y ppa:ubuntu-desktop/gnome-3-26
      apt -y update
