name: inotip-buyer
version: "1.0.0"
summary: Hello World Electron app
description: |
  Simple Hello World Electron app as an example
grade: stable
confinement: classic

apps:
  hello-node-snap:
    command: bin/hello-node-snap
    plugs: [network]

parts:
  hello-node-snap:
    plugin: nodejs
    node-packages:
      - hello-node-snap
