name: inotip-buyer
version: "1.0.0"
summary: Hello World Electron app
description: |
  Simple Hello World Electron app as an example
  
grade: stable
confinement: classic

apps:
  hello:
    command: bin/hello
    
parts:
  gnome:
    plugin: nil
    build-packages:
      - software-properties-common
    override-pull: |
      add-apt-repository -y ppa:ubuntu-desktop/gnome-3-26
      apt -y update
