name: inotip
summary: A fork of youtube-dl with additional features and patches
description: Download inotip and patches addition to the latest.
version: 1.0
grade: stable
confinement: strict
base: core22

#apps:
#  yt-dlp:
#    command: bin/yt-dlp
#    plugs: [home, network, network-bind, removable-media]

#parts:
#  yt-dlp:
#    plugin: python
#    source: https://github.com/yt-dlp/yt-dlp.git
