name: inotip-buyer
version: "1.0.0"
summary: Hello World Electron app
description: |
  Simple Hello World Electron app as an example
  
grade: stable
confinement: classic

apps:
  electron-packager-hello-world:
      command: electron-quick-start/electron-quick-start --no-sandbox
      plugs:
      - browser-support
      - network
      - network-bind
      environment:
        # Correct the TMPDIR path for Chromium Framework/Electron to ensure
        # libappindicator has readable resources.
        TMPDIR: $XDG_RUNTIME_DIR
    
parts:
  gnome:
    plugin: nil
    build-packages:
      - software-properties-common
    override-pull: |
      add-apt-repository -y ppa:ubuntu-desktop/gnome-3-26
      apt -y update
